name: Build PDF and Release
on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Get the current date
      id: date
      run: echo "::set-output name=date::$(date +'v%Y.%m.%d')"

    - name: Create tag
      run: git tag ${{ steps.date.outputs.date }}
      
    - name: Push tag to repository
      run: git push origin ${{ steps.date.outputs.date }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Compile latex doc
      uses: xu-cheng/latex-action@v3
      with:
        root_file: main.tex

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: main.pdf
        tag_name: ${{ steps.date.outputs.date }}